// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDownloadedUpdate() {
  return window['go']['main']['App']['ApplyDownloadedUpdate']();
}

export function CheckContextMenuExists() {
  return window['go']['main']['App']['CheckContextMenuExists']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadLatestUpdate() {
  return window['go']['main']['App']['DownloadLatestUpdate']();
}

export function GetDownloadsDir() {
  return window['go']['main']['App']['GetDownloadsDir']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function SetContextMenuEnabled(arg1) {
  return window['go']['main']['App']['SetContextMenuEnabled'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartSharing(arg1) {
  return window['go']['main']['App']['StartSharing'](arg1);
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}
