// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckContextMenuExists() {
  return window['go']['main']['App']['CheckContextMenuExists']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function SetContextMenuEnabled(arg1) {
  return window['go']['main']['App']['SetContextMenuEnabled'](arg1);
}

export function StartSharing(arg1) {
  return window['go']['main']['App']['StartSharing'](arg1);
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}
