// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckContextMenuExists():Promise<main.ContextMenuStatus>;

export function GetServerInfo():Promise<main.ServerInfo>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function SetContextMenuEnabled(arg1:boolean):Promise<void>;

export function StartSharing(arg1:string):Promise<main.ServerInfo>;

export function StopSharing():Promise<void>;
