// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyDownloadedUpdate():Promise<void>;

export function CheckContextMenuExists():Promise<main.ContextMenuStatus>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DownloadLatestUpdate():Promise<main.DownloadResult>;

export function GetDownloadsDir():Promise<string>;

export function GetServerInfo():Promise<main.ServerInfo>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function SetContextMenuEnabled(arg1:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartSharing(arg1:string):Promise<main.ServerInfo>;

export function StopSharing():Promise<void>;
